#!/usr/bin/env bash

function fetchToDisk {
  wget --quiet --tries=3 --timeout=10 --dns-timeout=5 --connect-timeout=5 --read-timeout=10 -O "temp.opml" "$1"
}

function delint {
  if [ ! -f "temp.opml" ]; then
      echo "temp.opml does not exist."
      return
  fi

  cat temp.opml | xmllint --nonet --noent --recover --xmlout --format - > "$1"
}

function mirrorTimestamp {
  echo "$(date --utc --iso-8601=seconds)Z"
}

function removeTemp {
  rm temp.opml
}

function fixCharacters {
  echo "fixCharacters - start"

  # Truncate strings of 2 or more spaces to a single space
  sed -i "s|\s{2,}| |gi" "$1"

  # Degree symbol
  sed -i "s|\xb0|&deg;|gi" "$1"

  # NDASH
  sed -i "s|\x26amp\x3bndash\x3b|\&ndash;|gi" "$1"

  # APOS 
  #sed -i "s|\x27|\&apos;|gi" "$1"
  sed -i "s|\x26\x2339\x3b|\&apos;|gi" "$1"

  #sed -i "s|\x26amp\x3b|\&amp;|gi" temp.opml
  #sed -i "s|\b\x26(?!(.+?)\x3b)\b|\&amp;|gi" temp.opml
  #sed -i "s|\s\x26\s| \&amp; |gi" temp.opml

  # Double double-quotes - breaks XML
  sed -i "s|\x22\x22|\"|gi" "$1"

  # AMP - Escape stuff that hasn't been escaped already
  sed -i "s|\x26(?!(?:apos|quot|[gl]t|amp|deg)\x3b|#)|&amp;|gi" "$1"

  # AMP - Naked ampersand between two words separated by space
  sed -i "s|\s\x26\s| \&amp; |gi" "$1"

  echo "fixCharacters - end"
}

function fixXMLDecl {
  echo "fixXMLDecl - start"

  # Change single quotes to double quotes on XML encoding declaration
  sed -i "s|encoding\x3d\x27UTF\x2d8\x27|encoding=\"UTF-8\"|gi" "$1"

  echo "fixXMLDecl - end"
}

function fixXMLStylesheet {
  echo "fixXMLStylesheet - start"

  # Remove simple stylesheet inclusion
  sed -i "s|\x3c\x3fxml\x2dstylesheet\stype\x3d\x22text\x2fxsl\x22\shref\x3d\x22(.+?)\x22\x3f\x3e||gi" "$1"
  sed -i "s|\x3c\x3fxml\x2dstylesheet\shref\x3d\x22(.+?)\x22\stype\x3d\x22text\x2fxsl\x22\x3f\x3e||gi" "$1"

  echo "fixXMLStylesheet - end"
}

function fixOPMLDecl {
  echo "fixOPMLDecl - start"

  # Change single quotes to double quotes on XML version declaration
  sed -i "s|version\x3d\x271\x2e0\x27|version=\"1.0\"|gi" "$1"

  # Change single quotes to double quotes on XML and OPML declaration
  sed -i "s|version\x3d\x271\x2e1\x27|version=\"1.1\"|gi" "$1"

  # Change single quotes to double quotes on XML and OPML declaration
  sed -i "s|version\x3d\x272\x2e0\x27|version=\"2.0\"|gi" "$1"

  # Replace single-quotes with double-quotes on OPML root element
  sed -i "s|\x3copml\sversion\x3d\x271\x2e0\x27\x3e|<opml version=\"1.0\">|gi" "$1"
  sed -i "s|\x3copml\sversion\x3d\x271\x2e1\x27\x3e|<opml version=\"1.1\">|gi" "$1"
  sed -i "s|\x3copml\sversion\x3d\x272\x2e0\x27\x3e|<opml version=\"2.0\">|gi" "$1"

  echo "fixOPMLDecl - end"
}


function fixXML {
  echo "fixXML - start"

  # /&gt; - Strange sequence
  sed -i "s|\x22\s{1,}\x2f\x26gt\x3b\s{1,}\x22|\"\"|gi" "$1"

  # Remove empty htmlUrl attributes
  sed -i "s|\s{1,}htmlUrl\x3d\x22\x22| htmlUrl=\"https://podcastindex.org/\"|gi" "$1"
  sed -i "s|\stext\x3d\x22\x22| text=\"Podcast\"|gi" "$1"

  # Remove UTM-tagging from links
  sed -i "s|(\x3f|\x26|\x26amp\x3b)utm\x5f(source|medium|campaign|content|term)\x3d([a-z0-9\x25\x2d]{1,})||gi" "$1"

  # Remove empty description attribute
  sed -i "s|\sdescription\x3d\x22\x22||gi" "$1"

  # Remove empty htmlUrl
  sed -i "s|\shtmlUrl\x3d\x22\x22||gi" "$1"

  # Adjust XML declaration to be standalone=yes
  sed -i "s|standalone\x3d\x22no\x22|standalone=\"yes\"|gi" "$1"

  echo "fixXML - end"
}

function removeURLFragments {
  echo "removeURLFragments - start"

  # Strip out GOOGLE_ABUSE_EXEMPTION
  sed -i "s|^http(s)?\x3a\x2f\x2f(.+?)(\x3f|\x26)google\x5fabuse\x3dGOOGLE\x5fABUSE\x5fEXEMPTION\x253DID\x253D(.*)|http$1://$2|gi" "$1"

  # Strip out "nw=0"
  sed -i "s|^http(s)?\x3a\x2f\x2f(.+?)(\x3f|\x26)nw\x3d\d{1,}|http$1://$2|gi" "$1"

  # Strip out "format=MP3_xxxK"
  sed -i "s|^http(s)?\x3a\x2f\x2f(.+?)(\x3f|\x26)format\x3dMP3\x5f\d{1,}K|http$1://$2|gi" "$1"

  # Strip out subscription keys (private subscriptions) "?key=asdf12345678"
  sed -i "s|\x3fkey\x3d([a-z0-9]{12})||gi" "$1"
  
  echo "removeURLFragments - end"
}

function removeStylesheet {
  # stylesheet reference (type, href)
  sed -i "s|\x3c\x3fxml\x2dstylesheet\stype\x3d\x22text\x2fxsl\x22\shref\x3d\x22(.+?)\x22\x3f\x3e\n||gi" "$1"

  # stylesheet referenct (href, type)
  sed -i "s|\x3c\x3fxml\x2dstylesheet\shref\x3d\x22(.+?)\x22\stype\x3d\x22text\x2fxsl\x22\x3f\x3e\n||gi" "$1"
  
}

function addMirrorTag {
  TIMESTAMP="$(date --iso-8601=seconds)Z"

  # OPML 1.0
  sed -i "s|\x3copml\x20version\x3d\x221\x2e0\x22\x3e|<!-- Mirrored at ${TIMESTAMP} from $1 to https://b19.se/data/opml/mirrored/$2 -->\n<opml version=\"1.0\">|gi" "$2"

  # OPML 1.1
  sed -i "s|\x3copml\x20version\x3d\x221\x2e1\x22\x3e|<!-- Mirrored at ${TIMESTAMP} from $1 to https://b19.se/data/opml/mirrored/$2 -->\n<opml version=\"1.1\">|gi" "$2"

  # OPML 2.0
  sed -i "s|\x3copml\x20version\x3d\x222\x2e0\x22\x3e|<!-- Mirrored at ${TIMESTAMP} from $1 to https://b19.se/data/opml/mirrored/$2 -->\n<opml version=\"2.0\">|gi" "$2"
}

function MirrorOPML {
  echo "Mirroring '$1' to '$2' ..."
  fetchToDisk "$1"
  fixXMLDecl "temp.opml" "$2"
  fixXMLStylesheet "temp.opml" "$2"
  fixOPMLDecl "temp.opml" "$2"
  fixXML "temp.opml" "$2"
  removeURLFragments "temp.opml"
  remoteStylesheet "temp.opml"
  fixCharacters "temp.opml" "$2"
  delint "$2"
  addMirrorTag "$1" "$2"
  removeTemp
}


MirrorOPML "http://www.cbc.ca/podcasts.opml" "cbc-ca-podcasts.opml"

MirrorOPML "http://edition.cnn.com/services/podcasting/CNN.opml" "cnn-edition.opml"

MirrorOPML "http://www.bbc.co.uk/podcasts.opml" "bbc-co-uk-podcasts.opml"
MirrorOPML "http://news.bbc.co.uk/rss/feeds.opml" "bbc-co-uk-news-rss-feeds.opml"

MirrorOPML "http://www.gigadial.net/public/opml/" "gigadial-pod.opml"

MirrorOPML "https://www.rtl.fr/podcasts.opml" "rtl-fr-podcasts.opml"

MirrorOPML "https://www.apapodcast.cz/podcast.opml" "apapodcast-cz-podcast.opml"

MirrorOPML "http://www.alohapodcast.com/APN.opml" "alohapodcast-apn.opml"

MirrorOPML "https://www.ibm.com/ibm/syndication/podcasts/us/en/index.opml" "ibm-podcasts.opml"

MirrorOPML "https://stats.podcastindex.org/v4vmusic.opml" "podcastindex-org-value4value-music.opml"

MirrorOPML "http://www.digitalpodcast.com/opml/digitalpodcast.opml" "digitalpodcast-com-directory.opml"
MirrorOPML "http://www.digitalpodcast.com/opml/digitalpodcastnew.opml" "digitalpodcast-com-50-newest.opml"
MirrorOPML "http://www.digitalpodcast.com/opml/digitalpodcastmostviewed.opml" "digitalpodcast-com-50-top-visits.opml"
MirrorOPML "http://www.digitalpodcast.com/opml/digitalpodcasttoprated.opml" "digitalpodcast-com-50-top-rated.opml"
MirrorOPML "http://www.digitalpodcast.com/opml/digitalpodcastmostsubscribed.opml" "digitalpodcast-com-50-most-subscribed.opml"

MirrorOPML "https://feeds.twit.tv/twitfeeds.opml" "twit-tv-twitfeeds.opml"
MirrorOPML "https://feeds.twit.tv/twitshows.opml" "twit-tv-twitshows.opml"
MirrorOPML "https://feeds.twit.tv/twitshows_video_hd.opml" "twit-tv-twitshows-video-hd.opml"

MirrorOPML "https://iosdevdirectory.com/opml/en/podcasts.opml" "iosdevdirectory-english-podcasts.opml"
MirrorOPML "https://iosdevdirectory.com/opml/es/podcasts.opml" "iosdevdirectory-spanish-podcasts.opml"
MirrorOPML "https://iosdevdirectory.com/opml/de/podcasts.opml" "iosdevdirectory-german-podcasts.opml"

MirrorOPML "http://ipodder.sourceforge.net/opml/ipodder-aegrumet.opml" "ipodder-sourceforge-net-ipodder-aegrumet.opml"
MirrorOPML "http://ipodder.sourceforge.net/opml/ipodder-gtk.opml" "ipodder-sourceforge-net-ipodder-gtk.opml"
MirrorOPML "http://ipodder.sourceforge.net/opml/ipodder.opml" "ipodder-sourceforge-net-ipodder.opml"

MirrorOPML "http://s3.amazonaws.com/radio2/communityReadingList.opml" "radio2-communityReadingList.opml"

MirrorOPML "http://podcasts.divergence-fm.org/podcasts.opml" "divergence-fm-podcasts.opml"

MirrorOPML "http://hosting.opml.org/dnorman/educationpodcasts.opml" "opml-org-dnorman-educationpodcasts.opml"
MirrorOPML "http://ladyofsituations.com/custom/people.opml" "ladyofsituations-custom-people.opml"
MirrorOPML "http://media.phlow.de/download/rss/podcast.opml" "phlow-de-podcasts.opml"
MirrorOPML "http://mirrors.fe.up.pt/kde-applicationdata/amarok/podcast_directory/developer_podcasts.opml" "amarok-developer_podcasts.opml"
MirrorOPML "http://nevillehobson.com/pubfiles/060508-NH-primary1-exp.opml" "nevillehobson-com-060508-NH-primary1-exp.opml"
MirrorOPML "http://rasterweb.net/raster/feeds/wisconsin.opml" "rasterweb-net-wisconsin.opml"
MirrorOPML "http://rss.sina.com.cn/sina_all_opml.xml" "sina-com-cn-all.opml"
MirrorOPML "http://www.marshallk.com/politicalaudio.aspx.xml" "marshalls-politicalaudio.opml"
MirrorOPML "https://ainali.com/listening/feed.opml" "ainali-listening.opml"
MirrorOPML "https://chillr.de/wp-content/uploads/Podcast20150707.opml" "chillr-de-podcast20150707.opml"
MirrorOPML "https://chrisabraham.com/opml/at_download/file" "chrisabreaham.opml"
MirrorOPML "https://dave.sobr.org/enc/1662343807.433_polishpodcastdirectoryopml.xml" "podkasty-info-katalog-podkastow.opml"
MirrorOPML "https://defaria.com/podcasts.opml" "defaria-podcasts.opml"
MirrorOPML "https://dhruv-sharma.ovh/files/podcasts.opml" "dhruv-sharma.opml"
MirrorOPML "https://digiper.com/dl/digiper.opml" "digiper.opml"
MirrorOPML "https://inkdroid.org/podcasts/feed.opml" "inkdroid-podcasts.opml"
MirrorOPML "https://jchk.net/files/Podcasts.opml" "jchk-net-files-podcasts.opml"
MirrorOPML "https://blog.grdryn.me/podcasts-2016.opml" "grdryn-me-podcasts-2016.opml"
MirrorOPML "https://codeberg.org/nac/podcast-liste/raw/branch/main/podcasts.opml" "nac-podcast-liste.opml"
MirrorOPML "https://raw.githubusercontent.com/Cj-Malone/Linux-Podcasts/master/feeds.opml" "cj-malone-linux-podcasts.opml"
MirrorOPML "https://raw.githubusercontent.com/marklogic-community/feed/master/test-scripts/data/opml_podcast.opml" "marklogic-community.opml"
MirrorOPML "https://raw.githubusercontent.com/OpenScienceRadio/Open-Science-Radio-Shownotes/master/OSR021/Auszug_Wissenschaftspodcasts_MFR_2014-06-03.opml" "openscienceradio-20140603.opml"
MirrorOPML "https://raw.githubusercontent.com/topgold/listening/master/fm.opml" "topgold-fm.opml"
MirrorOPML "https://raw.githubusercontent.com/topgold/listening/master/fm.opml" "topgold.opml"
MirrorOPML "https://raw.githubusercontent.com/yasuharu519/opml/master/main.opml" "yasuhary519.opml"
MirrorOPML "https://raw.githubusercontent.com/nurkiewicz/nurkiewicz.com/master/src/overcast.opml" "nurkiewicz-com-overcast.opml"
MirrorOPML "https://gist.githubusercontent.com/tatsumoto-ren/1df342d5270680f3c9dca078a93298a4/raw/d885f6c2f6ba11076f1e7b5c930472925e050304/podcasts.opml" "tatsumoto-ren.opml"
MirrorOPML "https://gist.githubusercontent.com/2KAbhishek/2abf301bdb60c972457e5109fc99ed1c/raw/e13eeb8d821bdf2091e9fe0f46a5286bc3b2b19d/Podcasts.opml.xml" "2KAbhishek.opml"
MirrorOPML "https://gist.githubusercontent.com/jasontucker/697ed02f11ed39345e11686d2b04acef/raw/e3046566de3ddc7cc9ad241e82b583c3c52be0a6/jasons_podcast.opml" "jasontucker.opml"
MirrorOPML "https://gist.githubusercontent.com/barrieselack/6164714/raw/8eefb665b812c8bffee881ea4604a5991c7d4823/podcasts.opml" "barrieselack.opml"
MirrorOPML "https://gist.githubusercontent.com/kobusb/c48256a031ee8cadbdf26d6595d73eee/raw/7d855551365000f52a9da36bf75615b8698748fc/podcasts.opml" "kobusb.opml"
MirrorOPML "https://redecentralize.org/redigest/2022/kthxbye/redigest_feed_recommendations.opml" "redecentralize-redigest-feed-reccommendations.opml"
MirrorOPML "https://source.mcwhirter.io/craige/rcfiles/raw/branch/consensus/.gpodder.opml" "mcwhirter-craige-consensus-gpodder.opml"
MirrorOPML "https://typlog.com/podlist/opml.xml" "typlog-pod.opml"
MirrorOPML "https://welcometochina.com.au/wp-content/uploads/china-podcasts.opml" "welcomtochina-china-podcasts.opml"
MirrorOPML "https://wissenschaftspodcasts.de/opml-export/" "wissenschafts-podcasts.opml"
MirrorOPML "https://www.ancientfaith.com/feeds/podcasts.opml" "ancientfaith-podcasts.opml"
MirrorOPML "https://www.apreche.net/~apreche/podcasts.opml" "apreche-podcasts.opml"
MirrorOPML "http://www.andyrowell.net/files/podcastaddict_export_20180305_182255.opml" "andyrowell-net-podcastaddict-export-20180305-182255.opml"
MirrorOPML "https://raw.githubusercontent.com/Nogamara/blaugust-opml/master/output/blapril2020/blaugust.opml" "nogamara-blaugust.opml"

MirrorOPML "https://fyyd.de/user/altf4/collection/deutsch/opml" "fyyd-de-altf4-collection-deutsch.opml"
MirrorOPML "https://fyyd.de/user/dirkprimbs/collection/fotografiepodcasts/opml" "fyyd-de-dirkprimbs-collection-fotografiepodcasts.opml"
MirrorOPML "https://fyyd.de/user/dirkprimbs/collection/podcastpodcasts/opml" "fyyd-de-dirkprimbs-collection-podcastpodcasts.opml"
MirrorOPML "https://fyyd.de/user/emolotow/collection/f361eea6f2288b3b565324885c91290a/opml" "fyyd-de-emoltow-collection.opml"
MirrorOPML "https://fyyd.de/user/garneleh/collection/audiospass-fuer-kids-und-co/opml" "fyyd-de-garneleh-collection-audiospass-fuer-kids-und-co.opml"
MirrorOPML "https://fyyd.de/user/garneleh/collection/frauenstimmen-im-netz/opml" "fyyd-de-garneleh-collection-frauenstimmen-im-netz.opml"
MirrorOPML "https://fyyd.de/user/gglnx/collection/meine-podcasts/opml" "fyyd-de-gglnx-collection-meine-podcasts.opml"
MirrorOPML "https://fyyd.de/user/hoersuppe/collection/geschichte/opml" "fyyd-de-hoersuppe-collection-geschinchte.opml"
MirrorOPML "https://fyyd.de/user/hoersuppe/collection/hoersuppe/opml" "fyyd-de-hoersuppe-collection-hoersuppe.opml"
MirrorOPML "https://fyyd.de/user/hoersuppe/collection/holgis-podcasts/opml" "fyyd-de-hoersuppe-collection-holgis-podcasts.opml"
MirrorOPML "https://fyyd.de/user/hoersuppe/collection/podcasting/opml" "fyyd-de-hoersuppe-collection-podcasting.opml"
MirrorOPML "https://fyyd.de/user/hoersuppe/collection/podcasts-fuer-kinder/opml" "fyyd-de-hoersuppe-collection-podasts-fuer-kinder.opml"
MirrorOPML "https://fyyd.de/user/hoersuppe/collection/utopia/opml" "fyyd-de-hoersuppe-collection-utopia.opml"
MirrorOPML "https://fyyd.de/user/holgi/collection/holgi/opml" "fyyd-de-holgi-collection-holgi.opml"
MirrorOPML "https://fyyd.de/user/iwmm/collection/77c5dd6f7db4444989918a5726b90255/opml" "fyyd-de-iwmm-collection.opml"
MirrorOPML "https://fyyd.de/user/JaegersNet/collection/de-rpg-podcasts/opml" "fyyd-de-jaegersnet-collection-de-rpg-podcasts.opml"
MirrorOPML "https://fyyd.de/user/limpc0re/collection/a64e2c64ea98e27fa996effb1d44af0f/opml" "fyyd-de-limpc0re-collection.opml"
MirrorOPML "https://fyyd.de/user/MisterL/collection/32dc7ac001dadd43706168d80024d7bb/opml" "fyyd-de-misterl-collection-filme-serien.opml"
MirrorOPML "https://fyyd.de/user/MisterL/collection/6bb99465e345d025c4ffe8b8bd5f8ff6/opml" "fyyd-de-misterl-collection-albernes.opml"
MirrorOPML "https://fyyd.de/user/MisterL/collection/8303a30eaffb78e30781753fa08fc769/opml" "fyyd-de-misterl-collection-it.opml"
MirrorOPML "https://fyyd.de/user/MisterL/collection/9e39ab6ee95f5f4ba8b0c3368cd1828c/opml" "fyyd-de-misterl-collection-politik.opml"
MirrorOPML "https://fyyd.de/user/MisterL/collection/c50796e5a93ed2db202a6315780dc548/opml" "fyyd-de-misterl-collection-jura.opml"
MirrorOPML "https://fyyd.de/user/MisterL/collection/cae73c22ce49638a4b57b5a6eac2420d/opml" "fyyd-de-misterl-collection-belletristik.opml"
MirrorOPML "https://fyyd.de/user/ophmoph/collection/36c66142c31e4cd8edbe74c6b82b5483/opml" "fyyd-de-ophmoph-collection.opml"
MirrorOPML "https://fyyd.de/user/Podstock/collection/podstock2018/opml" "fyyd-de-podstock-collection-podstock2018.opml"
MirrorOPML "https://fyyd.de/user/rebel/collection/997f494a3a31d9885acd820499c0439a/opml" "fyyd-de-rebel-collecion.opml"
MirrorOPML "https://fyyd.de/user/Sliebschner/collection/comic-podcasts/opml" "fyyd-de-sliebschner-collection-comic-podcasts.opml"

MirrorOPML "https://lists.pocketcasts.com/20-under-20.opml" "pocketcasts-com-20-under-20.opml"
MirrorOPML "https://lists.pocketcasts.com/20under20.opml" "pocketcasts-com-20under20.opml"
MirrorOPML "https://lists.pocketcasts.com/abc.opml" "pocketcasts-com-abc.opml"
MirrorOPML "https://lists.pocketcasts.com/accompaniments.opml" "pocketcasts-com-accompaniments.opml"
MirrorOPML "https://lists.pocketcasts.com/addressingracism.opml" "pocketcasts-com-addressing-racism.opml"
MirrorOPML "https://lists.pocketcasts.com/ai-revolution.opml" "pocketcasts-com-ai-revolution.opml"
MirrorOPML "https://lists.pocketcasts.com/americanpublicmedia.opml" "pocketcasts-com-american-public-media.opml"
MirrorOPML "https://lists.pocketcasts.com/arielle-nissenblatt.opml" "pocketcasts-com-arielle-nissenblatt.opml"
MirrorOPML "https://lists.pocketcasts.com/audioboom.opml" "pocketcasts-com-audioboom.opml"
MirrorOPML "https://lists.pocketcasts.com/audiovisual.opml" "pocketcasts-com-audiovisual.opml"
MirrorOPML "https://lists.pocketcasts.com/australianabc.opml" "pocketcasts-com-australian-abc.opml"
MirrorOPML "https://lists.pocketcasts.com/Australian-Broadcasting-Corporation.opml" "pocketcasts-com-australian-broadcasting-corporation.opml"
MirrorOPML "https://lists.pocketcasts.com/bbc.opml" "pocketcasts-com-bbc.opml"
MirrorOPML "https://lists.pocketcasts.com/beachreads.opml" "pocketcasts-com-beachreads.opml"
MirrorOPML "https://lists.pocketcasts.com/best-of-2016.opml" "pocketcasts-com-best-of-2016.opml"
MirrorOPML "https://lists.pocketcasts.com/best-of-2019.opml" "pocketcasts-com-best-of-2019.opml"
MirrorOPML "https://lists.pocketcasts.com/betterbedtime.opml" "pocketcasts-com-better-bedtime.opml"
MirrorOPML "https://lists.pocketcasts.com/biopods.opml" "pocketcasts-com-biopods.opml"
MirrorOPML "https://lists.pocketcasts.com/bloody-fm-2023.opml" "pocketcasts-com-bloody-fm-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/brain-matters.opml" "pocketcasts-com-brain-matters.opml"
MirrorOPML "https://lists.pocketcasts.com/bridgettodd.opml" "pocketcasts-com-bridgettodd.opml"
MirrorOPML "https://lists.pocketcasts.com/c13originals-2022.opml" "pocketcasts-com-c13-originals-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/carolinecrampton.opml" "pocketcasts-com-caroline-crampton.opml"
MirrorOPML "https://lists.pocketcasts.com/catpockets.opml" "pocketcasts-com-catpockets.opml"
MirrorOPML "https://lists.pocketcasts.com/cbc-podcasts-2023.opml" "pocketcasts-com-cbc-podcasts-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/cbc.opml" "pocketcasts-com-cbc.opml"
MirrorOPML "https://lists.pocketcasts.com/celebratingblackhistorymonth.opml" "pocketcasts-com-celebrating-black-history-month.opml"
MirrorOPML "https://lists.pocketcasts.com/changelog-2023.opml" "pocketcasts-com-changelog-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/cnn-2022.opml" "pocketcasts-com-cnn-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/coronavirus.opml" "pocketcasts-com-coronavirus.opml"
MirrorOPML "https://lists.pocketcasts.com/creative-conversations.opml" "pocketcasts-com-creative-conversations.opml"
MirrorOPML "https://lists.pocketcasts.com/crimetime.opml" "pocketcasts-com-crime-time.opml"
MirrorOPML "https://lists.pocketcasts.com/criticalfrequency.opml" "pocketcasts-com-critical-frequency.opml"
MirrorOPML "https://lists.pocketcasts.com/crooked-media-highlight-2022.opml" "pocketcasts-com-crooked-media-highlight-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/curtco.opml" "pocketcasts-com-curtco.opml"
MirrorOPML "https://lists.pocketcasts.com/dcpentertainment.opml" "pocketcasts-com-dcp-entertainment.opml"
MirrorOPML "https://lists.pocketcasts.com/divestudios.opml" "pocketcasts-com-dive-studios.opml"
MirrorOPML "https://lists.pocketcasts.com/dontboo.opml" "pocketcasts-com-dont-boo.opml"
MirrorOPML "https://lists.pocketcasts.com/eariefiction.opml" "pocketcasts-com-earie-fiction.opml"
MirrorOPML "https://lists.pocketcasts.com/earios.opml" "pocketcasts-com-earios.opml"
MirrorOPML "https://lists.pocketcasts.com/earthday.opml" "pocketcasts-com-earthday.opml"
MirrorOPML "https://lists.pocketcasts.com/earwolf-2022.opml" "pocketcasts-com-earwolf-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/earwolf.opml" "pocketcasts-com-earwolf.opml"
MirrorOPML "https://lists.pocketcasts.com/environment-day-2023.opml" "pocketcasts-com-world-environment-day-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/eone.opml" "pocketcasts-com-eone.opml"
MirrorOPML "https://lists.pocketcasts.com/exactly-right-2023.opml" "pocketcasts-com-exactly-right-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/fableandfolly.opml" "pocketcasts-com-fable-and-folley.opml"
MirrorOPML "https://lists.pocketcasts.com/fable-and-folly-2023.opml" "pocketcasts-com-fable-and-folley-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/featured.opml" "pocketcasts-com-featured.opml"
MirrorOPML "https://lists.pocketcasts.com/femalefocused.opml" "pocketcasts-com-female-focused.opml"
MirrorOPML "https://lists.pocketcasts.com/financial-times-2022.opml" "pocketcasts-com-financial-times-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/foreverdog.opml" "pocketcasts-com-foreverdog.opml"
MirrorOPML "https://lists.pocketcasts.com/forthekids.opml" "pocketcasts-com-for-the-kids.opml"
MirrorOPML "https://lists.pocketcasts.com/frequency.opml" "pocketcasts-com-frequency.opml"
MirrorOPML "https://lists.pocketcasts.com/ftb-lgbtq.opml" "pocketcasts-com-ftb-lgbtq.opml"
MirrorOPML "https://lists.pocketcasts.com/gamenight.opml" "pocketcasts-com-gamenight.opml"
MirrorOPML "https://lists.pocketcasts.com/geek-speak.opml" "pocketcasts-com-geek-speak.opml"
MirrorOPML "https://lists.pocketcasts.com/ghoulishtales.opml" "pocketcasts-com-ghoulish-tales.opml"
MirrorOPML "https://lists.pocketcasts.com/gottolisten.opml" "pocketcasts-com-got-to-listen.opml"
MirrorOPML "https://lists.pocketcasts.com/green-scene.opml" "pocketcasts-com-green-scene.opml"
MirrorOPML "https://lists.pocketcasts.com/grounded.opml" "pocketcasts-com-grounded.opml"
MirrorOPML "https://lists.pocketcasts.com/guiltypleasures.opml" "pocketcasts-com-guilty-pleasures.opml"
MirrorOPML "https://lists.pocketcasts.com/hair-raising-tales.opml" "pocketcasts-com-hair-raising-tales.opml"
MirrorOPML "https://lists.pocketcasts.com/happy-halloween-2022.opml" "pocketcasts-com-happy-halloween-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/havealaugh.opml" "pocketcasts-com-have-a-laugh.opml"
MirrorOPML "https://lists.pocketcasts.com/hbs-podcast-network-2022.opml" "pocketcasts-com-hbs-podcast-network-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/headgum.opml" "pocketcasts-com-headgum.opml"
MirrorOPML "https://lists.pocketcasts.com/hitpoints.opml" "pocketcasts-com-hitpoints.opml"
MirrorOPML "https://lists.pocketcasts.com/holidaysurvivalguide.opml" "pocketcasts-com-holiday-survival-guide.opml"
MirrorOPML "https://lists.pocketcasts.com/imperativeentertainment.opml" "pocketcasts-com-imperative-entertainment.opml"
MirrorOPML "https://lists.pocketcasts.com/jameskim.opml" "pocketcasts-com-james-kim.opml"
MirrorOPML "https://lists.pocketcasts.com/keepplaying.opml" "pocketcasts-com-keep-playing.opml"
MirrorOPML "https://lists.pocketcasts.com/kids.opml" "pocketcasts-com-kids.opml"
MirrorOPML "https://lists.pocketcasts.com/kuow-2023.opml" "pocketcasts-com-kuow-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/laist-studios-2023.opml" "pocketcasts-com-laist-studios-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/lantiguawilliamsco.opml" "pocketcasts-com-lantigua-williams-co.opml"
MirrorOPML "https://lists.pocketcasts.com/latinxspotlight.opml" "pocketcasts-com-latinx-spotlight.opml"
MirrorOPML "https://lists.pocketcasts.com/lauramayer.opml" "pocketcasts-com-laura-mayer.opml"
MirrorOPML "https://lists.pocketcasts.com/laurenober.opml" "pocketcasts-com-lauren-ober.opml"
MirrorOPML "https://lists.pocketcasts.com/laurenspohrer.opml" "pocketcasts-com-lauren-spohrer.opml"
MirrorOPML "https://lists.pocketcasts.com/learn-on-the-go.opml" "pocketcasts-com-learn-on-the-go.opml"
MirrorOPML "https://lists.pocketcasts.com/lemonada.opml" "pocketcasts-com-lemonada.opml"
MirrorOPML "https://lists.pocketcasts.com/letschat.opml" "pocketcasts-com-lets-chat.opml"
MirrorOPML "https://lists.pocketcasts.com/letstalk.opml" "pocketcasts-com-lets-talk.opml"
MirrorOPML "https://lists.pocketcasts.com/lgbtqueue.opml" "pocketcasts-com-lgbt-queue.opml"
MirrorOPML "https://lists.pocketcasts.com/lgbtqueue2020.opml" "pocketcasts-com-lgbt-queue-2020.opml"
MirrorOPML "https://lists.pocketcasts.com/lgbtqiaplus-creators.opml" "pocketcasts-com-lgbtqiaplus-creators.opml"
MirrorOPML "https://lists.pocketcasts.com/lippmedia.opml" "pocketcasts-com-lipp-media.opml"
MirrorOPML "https://lists.pocketcasts.com/listenersbeware.opml" "pocketcasts-com-listeners-beware.opml"
MirrorOPML "https://lists.pocketcasts.com/lit-listens.opml" "pocketcasts-com-lit-listens.opml"
MirrorOPML "https://lists.pocketcasts.com/lookingback.opml" "pocketcasts-com-looking-back.opml"
MirrorOPML "https://lists.pocketcasts.com/magic-malice-mayhem.opml" "pocketcasts-com-magic-malice-mayhem.opml"
MirrorOPML "https://lists.pocketcasts.com/marquesbrownlee.opml" "pocketcasts-com-marques-brown-lee.opml"
MirrorOPML "https://lists.pocketcasts.com/mattgourley.opml" "pocketcasts-com-matt-gourley.opml"
MirrorOPML "https://lists.pocketcasts.com/maxfun.opml" "pocketcasts-com-maxfun.opml"
MirrorOPML "https://lists.pocketcasts.com/maximumfun.opml" "pocketcasts-com-maximum-fun.opml"
MirrorOPML "https://lists.pocketcasts.com/may-the-4th.opml" "pocketcasts-com-may-the-4th.opml"
MirrorOPML "https://lists.pocketcasts.com/mealtime.opml" "pocketcasts-com-mealtime.opml"
MirrorOPML "https://lists.pocketcasts.com/mentalhealth.opml" "pocketcasts-com-mentalhealth.opml"
MirrorOPML "https://lists.pocketcasts.com/message-heard-2023.opml" "pocketcasts-com-message-heard-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/mixtapes.opml" "pocketcasts-com-mixtapes.opml"
MirrorOPML "https://lists.pocketcasts.com/multitude.opml" "pocketcasts-com-multitude.opml"
MirrorOPML "https://lists.pocketcasts.com/neverendingqueue.opml" "pocketcasts-com-neverendingqueue.opml"
MirrorOPML "https://lists.pocketcasts.com/next-chapter-podcasts-2023.opml" "pocketcasts-com-next-chapter-podcasts-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/ozpod2017.opml" "pocketcasts-com-ozpod-2017.opml"
MirrorOPML "https://lists.pocketcasts.com/ozpod2018.opml" "pocketcasts-com-ozpod-2018.opml"
MirrorOPML "https://lists.pocketcasts.com/peterwells.opml" "pocketcasts-com-peter-wells.opml"
MirrorOPML "https://lists.pocketcasts.com/popcornandpodcasts.opml" "pocketcasts-com-popcornandpodcasts.opml"
MirrorOPML "https://lists.pocketcasts.com/popular.opml" "pocketcasts-com-popular.opml"
MirrorOPML "https://lists.pocketcasts.com/pushkin.opml" "pocketcasts-com-pushkin.opml"
MirrorOPML "https://lists.pocketcasts.com/qcode.opml" "pocketcasts-com-qcode.opml"
MirrorOPML "https://lists.pocketcasts.com/radiotopia.opml" "pocketcasts-com-radiotopia.opml"
MirrorOPML "https://lists.pocketcasts.com/radiotopia-2022.opml" "pocketcasts-com-radiotopia-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/rashikarao.opml" "pocketcasts-com-rashikarao.opml"
MirrorOPML "https://lists.pocketcasts.com/resolutions.opml" "pocketcasts-com-resolutions.opml"
MirrorOPML "https://lists.pocketcasts.com/romance.opml" "pocketcasts-com-romance.opml"
MirrorOPML "https://lists.pocketcasts.com/saadia-khan.opml" "pocketcasts-com-saadia-khan.opml"
MirrorOPML "https://lists.pocketcasts.com/scarscrabble.opml" "pocketcasts-com-scarscrabble.opml"
MirrorOPML "https://lists.pocketcasts.com/scarypods.opml" "pocketcasts-com-scary-pods.opml"
MirrorOPML "https://lists.pocketcasts.com/sci-fi-serials.opml" "pocketcasts-com-sci-fi-serials.opml"
MirrorOPML "https://lists.pocketcasts.com/seasonal-spotlight.opml" "pocketcasts-com-seasonal-spotlight.opml"
MirrorOPML "https://lists.pocketcasts.com/showmethemoney.opml" "pocketcasts-com-show-me-the-money.opml"
MirrorOPML "https://lists.pocketcasts.com/slate.opml" "pocketcasts-com-slate.opml"
MirrorOPML "https://lists.pocketcasts.com/sleightheholidays.opml" "pocketcasts-com-sleigh-the-holidays.opml"
MirrorOPML "https://lists.pocketcasts.com/socialdistancing.opml" "pocketcasts-com-social-distancing.opml"
MirrorOPML "https://lists.pocketcasts.com/sony-music-entertainment-2022.opml" "pocketcasts-com-sony-music-entertainment-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/sonypodcasts.opml" "pocketcasts-com-sony-podcasts.opml"
MirrorOPML "https://lists.pocketcasts.com/soundbites.opml" "pocketcasts-com-soundbites.opml"
MirrorOPML "https://lists.pocketcasts.com/soundbody.opml" "pocketcasts-com-soundbody.opml"
MirrorOPML "https://lists.pocketcasts.com/spokemedia.opml" "pocketcasts-com-spoke-media.opml"
MirrorOPML "https://lists.pocketcasts.com/stayresolute.opml" "pocketcasts-com-stay-resolute.opml"
MirrorOPML "https://lists.pocketcasts.com/storic-media-2023.opml" "pocketcasts-com-storic-media-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/studio71.opml" "pocketcasts-com-studio71.opml"
MirrorOPML "https://lists.pocketcasts.com/talkies.opml" "pocketcasts-com-talkies.opml"
MirrorOPML "https://lists.pocketcasts.com/the-last-of-us.opml" "pocketcasts-com-the-last-of-us.opml"
MirrorOPML "https://lists.pocketcasts.com/thelittleones.opml" "pocketcasts-com-the-little-ones.opml"
MirrorOPML "https://lists.pocketcasts.com/the-wnet-group-2022.opml" "pocketcasts-com-the-wnet-group-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/thepodglomerate.opml" "pocketcasts-com-the-podglomerate.opml"
MirrorOPML "https://lists.pocketcasts.com/thepodglomerate.opml" "pocketcasts-com-the-podglomerate.opml"
MirrorOPML "https://lists.pocketcasts.com/thereplyallmazdatests.opml" "pocketcasts-com-thereplyallmazdatests.opml"
MirrorOPML "https://lists.pocketcasts.com/top-100-of-2020.opml" "pocketcasts-com-top-100-of-2020.opml"
MirrorOPML "https://lists.pocketcasts.com/top-100-of-2021.opml" "pocketcasts-com-top-100-of-2021.opml"
MirrorOPML "https://lists.pocketcasts.com/top-100-of-2022.opml" "pocketcasts-com-top-100-of-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/top-australia-2019.opml" "pocketcasts-com-top-australia-2019.opml"
MirrorOPML "https://lists.pocketcasts.com/top-australia-2020.opml" "pocketcasts-com-top-australia-2020.opml"
MirrorOPML "https://lists.pocketcasts.com/top-podcasts-2019.opml" "pocketcasts-com-top-podcasts-2019.opml"
MirrorOPML "https://lists.pocketcasts.com/top-podcasts-2020.opml" "pocketcasts-com-top-podcasts-2020.opml"
MirrorOPML "https://lists.pocketcasts.com/top-podcasts-2021.opml" "pocketcasts-com-top-podcasts-2021.opml"
MirrorOPML "https://lists.pocketcasts.com/top-podcasts-2022.opml" "pocketcasts-com-top-podcasts-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/top-united-kingdom-2019.opml" "pocketcasts-com-top-united-kingdom-2019.opml"
MirrorOPML "https://lists.pocketcasts.com/trannaandthomas.opml" "pocketcasts-com-trannaandthomas.opml"
MirrorOPML "https://lists.pocketcasts.com/trending.opml" "pocketcasts-com-trending.opml"
MirrorOPML "https://lists.pocketcasts.com/truecrimeandlime.opml" "pocketcasts-com-truecrime-and-lime.opml"
MirrorOPML "https://lists.pocketcasts.com/tune-in.opml" "pocketcasts-com-tune-in.opml"
MirrorOPML "https://lists.pocketcasts.com/twit.opml" "pocketcasts-com-twit.opml"
MirrorOPML "https://lists.pocketcasts.com/vox.opml" "pocketcasts-com-vox.opml"
MirrorOPML "https://lists.pocketcasts.com/wbez-2023.opml" "pocketcasts-com-wbez-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/whatsnext.opml" "pocketcasts-com-whats-next.opml"
MirrorOPML "https://lists.pocketcasts.com/whetstone-2022.opml" "pocketcasts-com-whetstone-2022.opml"
MirrorOPML "https://lists.pocketcasts.com/women-on-wickedness.opml" "pocketcasts-com-women-on-wickedness.opml"
MirrorOPML "https://lists.pocketcasts.com/wondermedianetwork.opml" "pocketcasts-com-wonder-media-network.opml"
MirrorOPML "https://lists.pocketcasts.com/world-ufo-day-2023.opml" "pocketcasts-com-world-ufo-day-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/new-and-true-2023.opml" "pocketcasts-com-new-and-true-2023.opml"
MirrorOPML "https://lists.pocketcasts.com/trannaandthomas.opml" "pocketcasts-com-tranna-and-thomas.opml"

MirrorOPML "https://player.fm/en/featured/acoustic.opml" "player-fm-en-featured-acoustic.opml"
MirrorOPML "https://player.fm/en/featured/activism.opml" "player-fm-en-featured-activism.opml"
MirrorOPML "https://player.fm/en/featured/addiction.opml" "player-fm-en-featured-addiction.opml"
MirrorOPML "https://player.fm/en/featured/aging.opml" "player-fm-en-featured-aging.opml"
MirrorOPML "https://player.fm/en/featured/alcoholism.opml" "player-fm-en-featured-alcoholism.opml"
MirrorOPML "https://player.fm/en/featured/alternative.opml" "player-fm-en-featured-alternative.opml"
MirrorOPML "https://player.fm/en/featured/alternative-health.opml" "player-fm-en-featured-alternative-health.opml"
MirrorOPML "https://player.fm/en/featured/american-football.opml" "player-fm-en-featured-american-football.opml"
MirrorOPML "https://player.fm/en/featured/americana.opml" "player-fm-en-featured-americana.opml"
MirrorOPML "https://player.fm/en/featured/animals-and-pets.opml" "player-fm-en-featured-animals-and-pets.opml"
MirrorOPML "https://player.fm/en/featured/archery.opml" "player-fm-en-featured-archery.opml"
MirrorOPML "https://player.fm/en/featured/artificial-intelligence.opml" "player-fm-en-featured-artificial-intelligence.opml"
MirrorOPML "https://player.fm/en/featured/arts.opml" "player-fm-en-featured-arts.opml"
MirrorOPML "https://player.fm/en/featured/asmr.opml" "player-fm-en-featured-asmr.opml"
MirrorOPML "https://player.fm/en/featured/audio-drama.opml" "player-fm-en-featured-audio-drama.opml"
MirrorOPML "https://player.fm/en/featured/audiobooks.opml" "player-fm-en-featured-audiobooks.opml"
MirrorOPML "https://player.fm/en/featured/aussie-rules.opml" "player-fm-en-featured-aussie-rules.opml"
MirrorOPML "https://player.fm/en/featured/baseball.opml" "player-fm-en-featured-baseball.opml"
MirrorOPML "https://player.fm/en/featured/basketball.opml" "player-fm-en-featured-basketball.opml"
MirrorOPML "https://player.fm/en/featured/bedtime-stories.opml" "player-fm-en-featured-bedtime-stories.opml"
MirrorOPML "https://player.fm/en/featured/billiards.opml" "player-fm-en-featured-billiards.opml"
MirrorOPML "https://player.fm/en/featured/binge-worthy-audio-drama.opml" "player-fm-en-featured-binge-worthy-audio-drama.opml"
MirrorOPML "https://player.fm/en/featured/binge-worthy-documentary.opml" "player-fm-en-featured-binge-worthy-documentary.opml"
MirrorOPML "https://player.fm/en/featured/binge-worthy-fiction.opml" "player-fm-en-featured-binge-worthy-fiction.opml"
MirrorOPML "https://player.fm/en/featured/binge-worthy-horror.opml" "player-fm-en-featured-binge-worthy-horror.opml"
MirrorOPML "https://player.fm/en/featured/binge-worthy-sci-fi-fantasy.opml" "player-fm-en-featured-binge-worthy-sci-fi-fantasy.opml"
MirrorOPML "https://player.fm/en/featured/binge-worthy-true-crime.opml" "player-fm-en-featured-binge-worthy-true-crime.opml"
MirrorOPML "https://player.fm/en/featured/biohacking.opml" "player-fm-en-featured-biohacking.opml"
MirrorOPML "https://player.fm/en/featured/blues.opml" "player-fm-en-featured-blues.opml"
MirrorOPML "https://player.fm/en/featured/books-and-writing.opml" "player-fm-en-featured-books-and-writing.opml"
MirrorOPML "https://player.fm/en/featured/breaking-news.opml" "player-fm-en-featured-breaking-news.opml"
MirrorOPML "https://player.fm/en/featured/business.opml" "player-fm-en-featured-business.opml"
MirrorOPML "https://player.fm/en/featured/business-disciplines.opml" "player-fm-en-featured-business-disciplines.opml"
MirrorOPML "https://player.fm/en/featured/business-education.opml" "player-fm-en-featured-business-education.opml"
MirrorOPML "https://player.fm/en/featured/business-english.opml" "player-fm-en-featured-business-english.opml"
MirrorOPML "https://player.fm/en/featured/business-news.opml" "player-fm-en-featured-business-news.opml"
MirrorOPML "https://player.fm/en/featured/capitalism.opml" "player-fm-en-featured-capitalism.opml"
MirrorOPML "https://player.fm/en/featured/careers.opml" "player-fm-en-featured-careers.opml"
MirrorOPML "https://player.fm/en/featured/cinema.opml" "player-fm-en-featured-cinema.opml"
MirrorOPML "https://player.fm/en/featured/classical.opml" "player-fm-en-featured-classical.opml"
MirrorOPML "https://player.fm/en/featured/combat-sports.opml" "player-fm-en-featured-combat-sports.opml"
MirrorOPML "https://player.fm/en/featured/comedy.opml" "player-fm-en-featured-comedy.opml"
MirrorOPML "https://player.fm/en/featured/comics.opml" "player-fm-en-featured-comics.opml"
MirrorOPML "https://player.fm/en/featured/communities.opml" "player-fm-en-featured-communities.opml"
MirrorOPML "https://player.fm/en/featured/computer-science.opml" "player-fm-en-featured-computer-science.opml"
MirrorOPML "https://player.fm/en/featured/conspiracy-theories.opml" "player-fm-en-featured-conspiracy-theories.opml"
MirrorOPML "https://player.fm/en/featured/conversations.opml" "player-fm-en-featured-conversations.opml"
MirrorOPML "https://player.fm/en/featured/country.opml" "player-fm-en-featured-country.opml"
MirrorOPML "https://player.fm/en/featured/cricket.opml" "player-fm-en-featured-cricket.opml"
MirrorOPML "https://player.fm/en/featured/crowdfunding.opml" "player-fm-en-featured-crowdfunding.opml"
MirrorOPML "https://player.fm/en/featured/cryptocurrency.opml" "player-fm-en-featured-cryptocurrency.opml"
MirrorOPML "https://player.fm/en/featured/current-affairs.opml" "player-fm-en-featured-current-affairs.opml"
MirrorOPML "https://player.fm/en/featured/daily-news.opml" "player-fm-en-featured-daily-news.opml"
MirrorOPML "https://player.fm/en/featured/daily-tech-news.opml" "player-fm-en-featured-daily-tech-news.opml"
MirrorOPML "https://player.fm/en/featured/data-science.opml" "player-fm-en-featured-data-science.opml"
MirrorOPML "https://player.fm/en/featured/diabetes.opml" "player-fm-en-featured-diabetes.opml"
MirrorOPML "https://player.fm/en/featured/disability.opml" "player-fm-en-featured-disability.opml"
MirrorOPML "https://player.fm/en/featured/disc-golf.opml" "player-fm-en-featured-disc-golf.opml"
MirrorOPML "https://player.fm/en/featured/documentaries.opml" "player-fm-en-featured-documentaries.opml"
MirrorOPML "https://player.fm/en/featured/drum-and-bass.opml" "player-fm-en-featured-drum-and-bass.opml"
MirrorOPML "https://player.fm/en/featured/drumming.opml" "player-fm-en-featured-drumming.opml"
MirrorOPML "https://player.fm/en/featured/eclectic.opml" "player-fm-en-featured-eclectic.opml"
MirrorOPML "https://player.fm/en/featured/education.opml" "player-fm-en-featured-education.opml"
MirrorOPML "https://player.fm/en/featured/electronic.opml" "player-fm-en-featured-electronic.opml"
MirrorOPML "https://player.fm/en/featured/endurance-sports.opml" "player-fm-en-featured-endurance-sports.opml"
MirrorOPML "https://player.fm/en/featured/entertainment.opml" "player-fm-en-featured-entertainment.opml"
MirrorOPML "https://player.fm/en/featured/entertainment-industry.opml" "player-fm-en-featured-entertainment-industry.opml"
MirrorOPML "https://player.fm/en/featured/entrepreneur.opml" "player-fm-en-featured-entrepreneur.opml"
MirrorOPML "https://player.fm/en/featured/entrepreneur-lifestyle.opml" "player-fm-en-featured-entrepreneur-lifestyle.opml"
MirrorOPML "https://player.fm/en/featured/environment.opml" "player-fm-en-featured-environment.opml"
MirrorOPML "https://player.fm/en/featured/equestrian.opml" "player-fm-en-featured-equestrian.opml"
MirrorOPML "https://player.fm/en/featured/esports.opml" "player-fm-en-featured-esports.opml"
MirrorOPML "https://player.fm/en/featured/eurovision.opml" "player-fm-en-featured-eurovision.opml"
MirrorOPML "https://player.fm/en/featured/facts-and-trivia.opml" "player-fm-en-featured-facts-and-trivia.opml"
MirrorOPML "https://player.fm/en/featured/family.opml" "player-fm-en-featured-family.opml"
MirrorOPML "https://player.fm/en/featured/fantasy-sports.opml" "player-fm-en-featured-fantasy-sports.opml"
MirrorOPML "https://player.fm/en/featured/fascinating-people.opml" "player-fm-en-featured-fascinating-people.opml"
MirrorOPML "https://player.fm/en/featured/fashion-and-beauty.opml" "player-fm-en-featured-fashion-and-beauty.opml"
MirrorOPML "https://player.fm/en/featured/fintech.opml" "player-fm-en-featured-fintech.opml"
MirrorOPML "https://player.fm/en/featured/firefighting.opml" "player-fm-en-featured-firefighting.opml"
MirrorOPML "https://player.fm/en/featured/fitness.opml" "player-fm-en-featured-fitness.opml"
MirrorOPML "https://player.fm/en/featured/folk.opml" "player-fm-en-featured-folk.opml"
MirrorOPML "https://player.fm/en/featured/food-and-beverage.opml" "player-fm-en-featured-food-and-beverage.opml"
MirrorOPML "https://player.fm/en/featured/future-trends.opml" "player-fm-en-featured-future-trends.opml"
MirrorOPML "https://player.fm/en/featured/gaa.opml" "player-fm-en-featured-gaa.opml"
MirrorOPML "https://player.fm/en/featured/gadgets.opml" "player-fm-en-featured-gadgets.opml"
MirrorOPML "https://player.fm/en/featured/games-and-gambling.opml" "player-fm-en-featured-games-and-gambling.opml"
MirrorOPML "https://player.fm/en/featured/geekery.opml" "player-fm-en-featured-geekery.opml"
MirrorOPML "https://player.fm/en/featured/golf.opml" "player-fm-en-featured-golf.opml"
MirrorOPML "https://player.fm/en/featured/gospel-music.opml" "player-fm-en-featured-gospel-music.opml"
MirrorOPML "https://player.fm/en/featured/guitar.opml" "player-fm-en-featured-guitar.opml"
MirrorOPML "https://player.fm/en/featured/gymnastics.opml" "player-fm-en-featured-gymnastics.opml"
MirrorOPML "https://player.fm/en/featured/handball.opml" "player-fm-en-featured-handball.opml"
MirrorOPML "https://player.fm/en/featured/health-and-well-being.opml" "player-fm-en-featured-health-and-well-being.opml"
MirrorOPML "https://player.fm/en/featured/health-care.opml" "player-fm-en-featured-health-care.opml"
MirrorOPML "https://player.fm/en/featured/health-news.opml" "player-fm-en-featured-health-news.opml"
MirrorOPML "https://player.fm/en/featured/hiphop.opml" "player-fm-en-featured-hiphop.opml"
MirrorOPML "https://player.fm/en/featured/hobbies.opml" "player-fm-en-featured-hobbies.opml"
MirrorOPML "https://player.fm/en/featured/hockey.opml" "player-fm-en-featured-hockey.opml"
MirrorOPML "https://player.fm/en/featured/holidays.opml" "player-fm-en-featured-holidays.opml"
MirrorOPML "https://player.fm/en/featured/horror-stories.opml" "player-fm-en-featured-horror-stories.opml"
MirrorOPML "https://player.fm/en/featured/humanities-education.opml" "player-fm-en-featured-humanities-education.opml"
MirrorOPML "https://player.fm/en/featured/immigration.opml" "player-fm-en-featured-immigration.opml"
MirrorOPML "https://player.fm/en/featured/industries.opml" "player-fm-en-featured-industries.opml"
MirrorOPML "https://player.fm/en/featured/intellectual-dark-web.opml" "player-fm-en-featured-intellectual-dark-web.opml"
MirrorOPML "https://player.fm/en/featured/interior-design.opml" "player-fm-en-featured-interior-design.opml"
MirrorOPML "https://player.fm/en/featured/international-news.opml" "player-fm-en-featured-international-news.opml"
MirrorOPML "https://player.fm/en/featured/it-industry.opml" "player-fm-en-featured-it-industry.opml"
MirrorOPML "https://player.fm/en/featured/j-pop.opml" "player-fm-en-featured-j-pop.opml"
MirrorOPML "https://player.fm/en/featured/jazz.opml" "player-fm-en-featured-jazz.opml"
MirrorOPML "https://player.fm/en/featured/journalism.opml" "player-fm-en-featured-journalism.opml"
MirrorOPML "https://player.fm/en/featured/k-pop.opml" "player-fm-en-featured-k-pop.opml"
MirrorOPML "https://player.fm/en/featured/lacrosse.opml" "player-fm-en-featured-lacrosse.opml"
MirrorOPML "https://player.fm/en/featured/language-learning.opml" "player-fm-en-featured-language-learning.opml"
MirrorOPML "https://player.fm/en/featured/latin-music.opml" "player-fm-en-featured-latin-music.opml"
MirrorOPML "https://player.fm/en/featured/law-of-attraction.opml" "player-fm-en-featured-law-of-attraction.opml"
MirrorOPML "https://player.fm/en/featured/leadership.opml" "player-fm-en-featured-leadership.opml"
MirrorOPML "https://player.fm/en/featured/lifestyle.opml" "player-fm-en-featured-lifestyle.opml"
MirrorOPML "https://player.fm/en/featured/marketing.opml" "player-fm-en-featured-marketing.opml"
MirrorOPML "https://player.fm/en/featured/math.opml" "player-fm-en-featured-math.opml"
MirrorOPML "https://player.fm/en/featured/mba.opml" "player-fm-en-featured-mba.opml"
MirrorOPML "https://player.fm/en/featured/media.opml" "player-fm-en-featured-media.opml"
MirrorOPML "https://player.fm/en/featured/medicine.opml" "player-fm-en-featured-medicine.opml"
MirrorOPML "https://player.fm/en/featured/mens-corner.opml" "player-fm-en-featured-mens-corner.opml"
MirrorOPML "https://player.fm/en/featured/mens-health.opml" "player-fm-en-featured-mens-health.opml"
MirrorOPML "https://player.fm/en/featured/mental-health.opml" "player-fm-en-featured-mental-health.opml"
MirrorOPML "https://player.fm/en/featured/metal.opml" "player-fm-en-featured-metal.opml"
MirrorOPML "https://player.fm/en/featured/minimalist.opml" "player-fm-en-featured-minimalist.opml"
MirrorOPML "https://player.fm/en/featured/motorsports.opml" "player-fm-en-featured-motorsports.opml"
MirrorOPML "https://player.fm/en/featured/music.opml" "player-fm-en-featured-music.opml"
MirrorOPML "https://player.fm/en/featured/music-industry.opml" "player-fm-en-featured-music-industry.opml"
MirrorOPML "https://player.fm/en/featured/musicians.opml" "player-fm-en-featured-musicians.opml"
MirrorOPML "https://player.fm/en/featured/mythology.opml" "player-fm-en-featured-mythology.opml"
MirrorOPML "https://player.fm/en/featured/natural-sciences.opml" "player-fm-en-featured-natural-sciences.opml"
MirrorOPML "https://player.fm/en/featured/netflix.opml" "player-fm-en-featured-netflix.opml"
MirrorOPML "https://player.fm/en/featured/news.opml" "player-fm-en-featured-news.opml"
MirrorOPML "https://player.fm/en/featured/news-and-entertainment.opml" "player-fm-en-featured-news-and-entertainment.opml"
MirrorOPML "https://player.fm/en/featured/news-talk.opml" "player-fm-en-featured-news-talk.opml"
MirrorOPML "https://player.fm/en/featured/nutrition.opml" "player-fm-en-featured-nutrition.opml"
MirrorOPML "https://player.fm/en/featured/occupational-therapy.opml" "player-fm-en-featured-occupational-therapy.opml"
MirrorOPML "https://player.fm/en/featured/oldies.opml" "player-fm-en-featured-oldies.opml"
MirrorOPML "https://player.fm/en/featured/operating-systems.opml" "player-fm-en-featured-operating-systems.opml"
MirrorOPML "https://player.fm/en/featured/paranormal.opml" "player-fm-en-featured-paranormal.opml"
MirrorOPML "https://player.fm/en/featured/personal-finances.opml" "player-fm-en-featured-personal-finances.opml"
MirrorOPML "https://player.fm/en/featured/piano.opml" "player-fm-en-featured-piano.opml"
MirrorOPML "https://player.fm/en/featured/politics.opml" "player-fm-en-featured-politics.opml"
MirrorOPML "https://player.fm/en/featured/pop.opml" "player-fm-en-featured-pop.opml"
MirrorOPML "https://player.fm/en/featured/pop-culture.opml" "player-fm-en-featured-pop-culture.opml"
MirrorOPML "https://player.fm/en/featured/pregnancy.opml" "player-fm-en-featured-pregnancy.opml"
MirrorOPML "https://player.fm/en/featured/prog-languages.opml" "player-fm-en-featured-prog-languages.opml"
MirrorOPML "https://player.fm/en/featured/project-management.opml" "player-fm-en-featured-project-management.opml"
MirrorOPML "https://player.fm/en/featured/reggae.opml" "player-fm-en-featured-reggae.opml"
MirrorOPML "https://player.fm/en/featured/relationship.opml" "player-fm-en-featured-relationship.opml"
MirrorOPML "https://player.fm/en/featured/religion.opml" "player-fm-en-featured-religion.opml"
MirrorOPML "https://player.fm/en/featured/retirement.opml" "player-fm-en-featured-retirement.opml"
MirrorOPML "https://player.fm/en/featured/retro.opml" "player-fm-en-featured-retro.opml"
MirrorOPML "https://player.fm/en/featured/rock.opml" "player-fm-en-featured-rock.opml"
MirrorOPML "https://player.fm/en/featured/rugby.opml" "player-fm-en-featured-rugby.opml"
MirrorOPML "https://player.fm/en/featured/sci-fi-fantasy-stories.opml" "player-fm-en-featured-sci-fi-fantasy-stories.opml"
MirrorOPML "https://player.fm/en/featured/science.opml" "player-fm-en-featured-science.opml"
MirrorOPML "https://player.fm/en/featured/science-education.opml" "player-fm-en-featured-science-education.opml"
MirrorOPML "https://player.fm/en/featured/self-improvement.opml" "player-fm-en-featured-self-improvement.opml"
MirrorOPML "https://player.fm/en/featured/sexuality.opml" "player-fm-en-featured-sexuality.opml"
MirrorOPML "https://player.fm/en/featured/short-stories.opml" "player-fm-en-featured-short-stories.opml"
MirrorOPML "https://player.fm/en/featured/skateboarding.opml" "player-fm-en-featured-skateboarding.opml"
MirrorOPML "https://player.fm/en/featured/skating.opml" "player-fm-en-featured-skating.opml"
MirrorOPML "https://player.fm/en/featured/skeptic.opml" "player-fm-en-featured-skeptic.opml"
MirrorOPML "https://player.fm/en/featured/soccer.opml" "player-fm-en-featured-soccer.opml"
MirrorOPML "https://player.fm/en/featured/social-sciences.opml" "player-fm-en-featured-social-sciences.opml"
MirrorOPML "https://player.fm/en/featured/society.opml" "player-fm-en-featured-society.opml"
MirrorOPML "https://player.fm/en/featured/software-development.opml" "player-fm-en-featured-software-development.opml"
MirrorOPML "https://player.fm/en/featured/soul.opml" "player-fm-en-featured-soul.opml"
MirrorOPML "https://player.fm/en/featured/soundtrack.opml" "player-fm-en-featured-soundtrack.opml"
MirrorOPML "https://player.fm/en/featured/specialized-news.opml" "player-fm-en-featured-specialized-news.opml"
MirrorOPML "https://player.fm/en/featured/sports.opml" "player-fm-en-featured-sports.opml"
MirrorOPML "https://player.fm/en/featured/sports-and-entertainment.opml" "player-fm-en-featured-sports-and-entertainment.opml"
MirrorOPML "https://player.fm/en/featured/sports-betting.opml" "player-fm-en-featured-sports-betting.opml"
MirrorOPML "https://player.fm/en/featured/sports-coaching.opml" "player-fm-en-featured-sports-coaching.opml"
MirrorOPML "https://player.fm/en/featured/sports-medicine.opml" "player-fm-en-featured-sports-medicine.opml"
MirrorOPML "https://player.fm/en/featured/storytelling.opml" "player-fm-en-featured-storytelling.opml"
MirrorOPML "https://player.fm/en/featured/survival.opml" "player-fm-en-featured-survival.opml"
MirrorOPML "https://player.fm/en/featured/taxation.opml" "player-fm-en-featured-taxation.opml"
MirrorOPML "https://player.fm/en/featured/teaching.opml" "player-fm-en-featured-teaching.opml"
MirrorOPML "https://player.fm/en/featured/tech.opml" "player-fm-en-featured-tech.opml"
MirrorOPML "https://player.fm/en/featured/tech-education.opml" "player-fm-en-featured-tech-education.opml"
MirrorOPML "https://player.fm/en/featured/tech-news.opml" "player-fm-en-featured-tech-news.opml"
MirrorOPML "https://player.fm/en/featured/tech-tips.opml" "player-fm-en-featured-tech-tips.opml"
MirrorOPML "https://player.fm/en/featured/tennis.opml" "player-fm-en-featured-tennis.opml"
MirrorOPML "https://player.fm/en/featured/travel.opml" "player-fm-en-featured-travel.opml"
MirrorOPML "https://player.fm/en/featured/true-crime.opml" "player-fm-en-featured-true-crime.opml"
MirrorOPML "https://player.fm/en/featured/true-stories.opml" "player-fm-en-featured-true-stories.opml"
MirrorOPML "https://player.fm/en/featured/tv.opml" "player-fm-en-featured-tv.opml"
MirrorOPML "https://player.fm/en/featured/ufos.opml" "player-fm-en-featured-ufos.opml"
MirrorOPML "https://player.fm/en/featured/ukulele.opml" "player-fm-en-featured-ukulele.opml"
MirrorOPML "https://player.fm/en/featured/urbanism.opml" "player-fm-en-featured-urbanism.opml"
MirrorOPML "https://player.fm/en/featured/varsity-teams.opml" "player-fm-en-featured-varsity-teams.opml"
MirrorOPML "https://player.fm/en/featured/venture-capital.opml" "player-fm-en-featured-venture-capital.opml"
MirrorOPML "https://player.fm/en/featured/video-game-music.opml" "player-fm-en-featured-video-game-music.opml"
MirrorOPML "https://player.fm/en/featured/video-games.opml" "player-fm-en-featured-video-games.opml"
MirrorOPML "https://player.fm/en/featured/voice-acting.opml" "player-fm-en-featured-voice-acting.opml"
MirrorOPML "https://player.fm/en/featured/volleyball.opml" "player-fm-en-featured-volleyball.opml"
MirrorOPML "https://player.fm/en/featured/womens-corner.opml" "player-fm-en-featured-womens-corner.opml"
MirrorOPML "https://player.fm/en/featured/womens-health.opml" "player-fm-en-featured-womens-health.opml"
MirrorOPML "https://player.fm/en/featured/youtube.opml" "player-fm-en-featured-youtube.opml"

MirrorOPML "https://player.fm/networks/1010-wins.opml" "player-fm-networks-1010-wins.opml"
MirrorOPML "https://player.fm/networks/1011-wcbs.opml" "player-fm-networks-1011-wcbs.opml"
MirrorOPML "https://player.fm/networks/1025-kzok.opml" "player-fm-networks-1025-kzok.opml"
MirrorOPML "https://player.fm/networks/1043-womc.opml" "player-fm-networks-1043-womc.opml"
MirrorOPML "https://player.fm/networks/1057-the-fan.opml" "player-fm-networks-1057-the-fan.opml"
MirrorOPML "https://player.fm/networks/1059-sunny-fm.opml" "player-fm-networks-1059-sunny-fm.opml"
MirrorOPML "https://player.fm/networks/1067-the-fan.opml" "player-fm-networks-1067-the-fan.opml"
MirrorOPML "https://player.fm/networks/1080-wtic-newstalk.opml" "player-fm-networks-1080-wtic-newstalk.opml"
MirrorOPML "https://player.fm/networks/2gb.opml" "player-fm-networks-2gb.opml"
MirrorOPML "https://player.fm/networks/3aw.opml" "player-fm-networks-3aw.opml"
MirrorOPML "https://player.fm/networks/3cr-community-radio.opml" "player-fm-networks-3cr-community-radio.opml"
MirrorOPML "https://player.fm/networks/3rrr-fm.opml" "player-fm-networks-3rrr-fm.opml"
MirrorOPML "https://player.fm/networks/5by5.opml" "player-fm-networks-5by5.opml"
MirrorOPML "https://player.fm/networks/670-the-score.opml" "player-fm-networks-670-the-score.opml"
MirrorOPML "https://player.fm/networks/830-wcco.opml" "player-fm-networks-830-wcco.opml"
MirrorOPML "https://player.fm/networks/923-the-fan.opml" "player-fm-networks-923-the-fan.opml"
MirrorOPML "https://player.fm/networks/925-xtu.opml" "player-fm-networks-925-xtu.opml"
MirrorOPML "https://player.fm/networks/929-the-game.opml" "player-fm-networks-929-the-game.opml"
MirrorOPML "https://player.fm/networks/937-the-fan.opml" "player-fm-networks-937-the-fan.opml"
MirrorOPML "https://player.fm/networks/93xrt.opml" "player-fm-networks-93xrt.opml"
MirrorOPML "https://player.fm/networks/947-fresh-fm.opml" "player-fm-networks-947-fresh-fm.opml"
MirrorOPML "https://player.fm/networks/971-amp-radio.opml" "player-fm-networks-971-amp-radio.opml"
MirrorOPML "https://player.fm/networks/971-the-ticket.opml" "player-fm-networks-971-the-ticket.opml"
MirrorOPML "https://player.fm/networks/981-wogl.opml" "player-fm-networks-981-wogl.opml"
MirrorOPML "https://player.fm/networks/985-kluc.opml" "player-fm-networks-985-kluc.opml"
MirrorOPML "https://player.fm/networks/985-the-sports-hub.opml" "player-fm-networks-985-the-sports-hub.opml"
MirrorOPML "https://player.fm/networks/987-kluv.opml" "player-fm-networks-987-kluv.opml"
MirrorOPML "https://player.fm/networks/997-now.opml" "player-fm-networks-997-now.opml"
MirrorOPML "https://player.fm/networks/abc-grandstand.opml" "player-fm-networks-abc-grandstand.opml"
MirrorOPML "https://player.fm/networks/abc-radio-national.opml" "player-fm-networks-abc-radio-national.opml"
MirrorOPML "https://player.fm/networks/afterbuzz-tv.opml" "player-fm-networks-afterbuzz-tv.opml"
MirrorOPML "https://player.fm/networks/al-jazeera-english.opml" "player-fm-networks-al-jazeera-english.opml"
MirrorOPML "https://player.fm/networks/alice-973.opml" "player-fm-networks-alice-973.opml"
MirrorOPML "https://player.fm/networks/alien-angel-podcast-network.opml" "player-fm-networks-alien-angel-podcast-network.opml"
MirrorOPML "https://player.fm/networks/all-things-comedy.opml" "player-fm-networks-all-things-comedy.opml"
MirrorOPML "https://player.fm/networks/amateur-scientist.opml" "player-fm-networks-amateur-scientist.opml"
MirrorOPML "https://player.fm/networks/amateur-traveler-podcast.opml" "player-fm-networks-amateur-traveler-podcast.opml"
MirrorOPML "https://player.fm/networks/american-public-media.opml" "player-fm-networks-american-public-media.opml"
MirrorOPML "https://player.fm/networks/amovetv.opml" "player-fm-networks-amovetv.opml"
MirrorOPML "https://player.fm/networks/amp-radio-1033.opml" "player-fm-networks-amp-radio-1033.opml"
MirrorOPML "https://player.fm/networks/arn-mix-fm.opml" "player-fm-networks-arn-mix-fm.opml"
MirrorOPML "https://player.fm/networks/atomic-rocket-studios.opml" "player-fm-networks-atomic-rocket-studios.opml"
# 2023-09-27 - empty MirrorOPML "https://player.fm/networks/audioboom.opml" "player-fm-networks-audioboom.opml"
MirrorOPML "https://player.fm/networks/australia-podcast-networks.opml" "player-fm-networks-australia-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/b96.opml" "player-fm-networks-b96.opml"
MirrorOPML "https://player.fm/networks/bald-move.opml" "player-fm-networks-bald-move.opml"
MirrorOPML "https://player.fm/networks/ball-hogs-radio-network.opml" "player-fm-networks-ball-hogs-radio-network.opml"
MirrorOPML "https://player.fm/networks/barbican.opml" "player-fm-networks-barbican.opml"
MirrorOPML "https://player.fm/networks/bbc-asian-network.opml" "player-fm-networks-bbc-asian-network.opml"
MirrorOPML "https://player.fm/networks/bbc-cbeebies.opml" "player-fm-networks-bbc-cbeebies.opml"
MirrorOPML "https://player.fm/networks/bbc-local-stations.opml" "player-fm-networks-bbc-local-stations.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-1.opml" "player-fm-networks-bbc-radio-1.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-1xtra.opml" "player-fm-networks-bbc-radio-1xtra.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-2.opml" "player-fm-networks-bbc-radio-2.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-3.opml" "player-fm-networks-bbc-radio-3.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-4-extra.opml" "player-fm-networks-bbc-radio-4-extra.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-4.opml" "player-fm-networks-bbc-radio-4.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-5-live.opml" "player-fm-networks-bbc-radio-5-live.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-6-music.opml" "player-fm-networks-bbc-radio-6-music.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-scotland.opml" "player-fm-networks-bbc-radio-scotland.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-ulster.opml" "player-fm-networks-bbc-radio-ulster.opml"
MirrorOPML "https://player.fm/networks/bbc-radio-wales.opml" "player-fm-networks-bbc-radio-wales.opml"
MirrorOPML "https://player.fm/networks/bbc-radio.opml" "player-fm-networks-bbc-radio.opml"
MirrorOPML "https://player.fm/networks/bbc-world-service.opml" "player-fm-networks-bbc-world-service.opml"
#MirrorOPML "https://player.fm/networks/bigfooty.opml" "player-fm-networks-bigfooty.opml"
MirrorOPML "https://player.fm/networks/boing-boing.opml" "player-fm-networks-boing-boing.opml"
MirrorOPML "https://player.fm/networks/business-networks.opml" "player-fm-networks-business-networks.opml"
MirrorOPML "https://player.fm/networks/canada-podcast-networks.opml" "player-fm-networks-canada-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/capital-public-radio.opml" "player-fm-networks-capital-public-radio.opml"
MirrorOPML "https://player.fm/networks/carolla-digital.opml" "player-fm-networks-carolla-digital.opml"
MirrorOPML "https://player.fm/networks/cave-comedy-club.opml" "player-fm-networks-cave-comedy-club.opml"
MirrorOPML "https://player.fm/networks/cbc-radio.opml" "player-fm-networks-cbc-radio.opml"
MirrorOPML "https://player.fm/networks/cbs-local-sports.opml" "player-fm-networks-cbs-local-sports.opml"
MirrorOPML "https://player.fm/networks/citr-radio.opml" "player-fm-networks-citr-radio.opml"
MirrorOPML "https://player.fm/networks/classic-live-105.opml" "player-fm-networks-classic-live-105.opml"
MirrorOPML "https://player.fm/networks/code-school.opml" "player-fm-networks-code-school.opml"
MirrorOPML "https://player.fm/networks/comic-vine.opml" "player-fm-networks-comic-vine.opml"
MirrorOPML "https://player.fm/networks/contact-talk-radio-network.opml" "player-fm-networks-contact-talk-radio-network.opml"
MirrorOPML "https://player.fm/networks/csicon.opml" "player-fm-networks-csicon.opml"
MirrorOPML "https://player.fm/networks/dabcc.opml" "player-fm-networks-dabcc.opml"
MirrorOPML "https://player.fm/networks/devchattv.opml" "player-fm-networks-devchattv.opml"
MirrorOPML "https://player.fm/networks/dvm-podcast-empire.opml" "player-fm-networks-dvm-podcast-empire.opml"
MirrorOPML "https://player.fm/networks/e-media-network.opml" "player-fm-networks-e-media-network.opml"
MirrorOPML "https://player.fm/networks/earwolf.opml" "player-fm-networks-earwolf.opml"
MirrorOPML "https://player.fm/networks/education-networks.opml" "player-fm-networks-education-networks.opml"
MirrorOPML "https://player.fm/networks/energy-1037.opml" "player-fm-networks-energy-1037.opml"
MirrorOPML "https://player.fm/networks/entertainment-networks.opml" "player-fm-networks-entertainment-networks.opml"
MirrorOPML "https://player.fm/networks/esnfm.opml" "player-fm-networks-esnfm.opml"
MirrorOPML "https://player.fm/networks/espn-radio.opml" "player-fm-networks-espn-radio.opml"
MirrorOPML "https://player.fm/networks/ewtn.opml" "player-fm-networks-ewtn.opml"
MirrorOPML "https://player.fm/networks/fbi-radio.opml" "player-fm-networks-fbi-radio.opml"
MirrorOPML "https://player.fm/networks/feral-audio.opml" "player-fm-networks-feral-audio.opml"
MirrorOPML "https://player.fm/networks/financial-times.opml" "player-fm-networks-financial-times.opml"
MirrorOPML "https://player.fm/networks/firearms-radio-network.opml" "player-fm-networks-firearms-radio-network.opml"
MirrorOPML "https://player.fm/networks/fm.opml" "player-fm-networks-fm.opml"
#MirrorOPML "https://player.fm/networks/focus-on-the-family.opml" "player-fm-networks-focus-on-the-family.opml"
MirrorOPML "https://player.fm/networks/for-immediate-release.opml" "player-fm-networks-for-immediate-release.opml"
MirrorOPML "https://player.fm/networks/foureyed-radio.opml" "player-fm-networks-foureyed-radio.opml"
MirrorOPML "https://player.fm/networks/frogpants-studios.opml" "player-fm-networks-frogpants-studios.opml"
MirrorOPML "https://player.fm/networks/fun-kids.opml" "player-fm-networks-fun-kids.opml"
MirrorOPML "https://player.fm/networks/g2v-productions.opml" "player-fm-networks-g2v-productions.opml"
MirrorOPML "https://player.fm/networks/gareth-stack.opml" "player-fm-networks-gareth-stack.opml"
MirrorOPML "https://player.fm/networks/geek-legacy.opml" "player-fm-networks-geek-legacy.opml"
MirrorOPML "https://player.fm/networks/general-networks.opml" "player-fm-networks-general-networks.opml"
MirrorOPML "https://player.fm/networks/generally-speaking-production-network.opml" "player-fm-networks-generally-speaking-production-network.opml"
MirrorOPML "https://player.fm/networks/germany-podcast-networks.opml" "player-fm-networks-germany-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/giant-bomb.opml" "player-fm-networks-giant-bomb.opml"
MirrorOPML "https://player.fm/networks/gimlet-media.opml" "player-fm-networks-gimlet-media.opml"
MirrorOPML "https://player.fm/networks/golden-spiral-media.opml" "player-fm-networks-golden-spiral-media.opml"
MirrorOPML "https://player.fm/networks/goodstufffm.opml" "player-fm-networks-goodstufffm.opml"
MirrorOPML "https://player.fm/networks/grantland.opml" "player-fm-networks-grantland.opml"
#MirrorOPML "https://player.fm/networks/grizzly-productions.opml" "player-fm-networks-grizzly-productions.opml"
MirrorOPML "https://player.fm/networks/guardian-radio-network.opml" "player-fm-networks-guardian-radio-network.opml"
MirrorOPML "https://player.fm/networks/health-and-well-being-networks.opml" "player-fm-networks-health-and-well-being-networks.opml"
MirrorOPML "https://player.fm/networks/heritage-radio-network.opml" "player-fm-networks-heritage-radio-network.opml"
MirrorOPML "https://player.fm/networks/howstuffworks.opml" "player-fm-networks-howstuffworks.opml"
MirrorOPML "https://player.fm/networks/ibm.opml" "player-fm-networks-ibm.opml"
MirrorOPML "https://player.fm/networks/idle-thumbs.opml" "player-fm-networks-idle-thumbs.opml"
MirrorOPML "https://player.fm/networks/indian-cowboy.opml" "player-fm-networks-indian-cowboy.opml"
MirrorOPML "https://player.fm/networks/infinite-guest.opml" "player-fm-networks-infinite-guest.opml"
MirrorOPML "https://player.fm/networks/ireland-podcast-networks.opml" "player-fm-networks-ireland-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/its-new-orleans.opml" "player-fm-networks-its-new-orleans.opml"
MirrorOPML "https://player.fm/networks/japan-podcast-networks.opml" "player-fm-networks-japan-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/jim-harold.opml" "player-fm-networks-jim-harold.opml"
MirrorOPML "https://player.fm/networks/joy-949.opml" "player-fm-networks-joy-949.opml"
MirrorOPML "https://player.fm/networks/jupiter-broadcasting.opml" "player-fm-networks-jupiter-broadcasting.opml"
MirrorOPML "https://player.fm/networks/kcbs-740-am-1069-fm.opml" "player-fm-networks-kcbs-740-am-1069-fm.opml"
MirrorOPML "https://player.fm/networks/kcrw.opml" "player-fm-networks-kcrw.opml"
MirrorOPML "https://player.fm/networks/kexp.opml" "player-fm-networks-kexp.opml"
MirrorOPML "https://player.fm/networks/kfrog.opml" "player-fm-networks-kfrog.opml"
MirrorOPML "https://player.fm/networks/khtk-sports-1140.opml" "player-fm-networks-khtk-sports-1140.opml"
MirrorOPML "https://player.fm/networks/kmox.opml" "player-fm-networks-kmox.opml"
MirrorOPML "https://player.fm/networks/knx-1070-newsradio.opml" "player-fm-networks-knx-1070-newsradio.opml"
MirrorOPML "https://player.fm/networks/kqed.opml" "player-fm-networks-kqed.opml"
MirrorOPML "https://player.fm/networks/kroq.opml" "player-fm-networks-kroq.opml"
MirrorOPML "https://player.fm/networks/kyw-newsradio-1060.opml" "player-fm-networks-kyw-newsradio-1060.opml"
MirrorOPML "https://player.fm/networks/kyxy-965.opml" "player-fm-networks-kyxy-965.opml"
MirrorOPML "https://player.fm/networks/legal-talk-network.opml" "player-fm-networks-legal-talk-network.opml"
MirrorOPML "https://player.fm/networks/legion-of-weirdos.opml" "player-fm-networks-legion-of-weirdos.opml"
MirrorOPML "https://player.fm/networks/librivox.opml" "player-fm-networks-librivox.opml"
MirrorOPML "https://player.fm/networks/lifestyle-networks.opml" "player-fm-networks-lifestyle-networks.opml"
MirrorOPML "https://player.fm/networks/lifestyle-podnetwork.opml" "player-fm-networks-lifestyle-podnetwork.opml"
MirrorOPML "https://player.fm/networks/loud-speakers-network.opml" "player-fm-networks-loud-speakers-network.opml"
MirrorOPML "https://player.fm/networks/mammoth-audio.opml" "player-fm-networks-mammoth-audio.opml"
MirrorOPML "https://player.fm/networks/maximum-fun.opml" "player-fm-networks-maximum-fun.opml"
MirrorOPML "https://player.fm/networks/minnesota-public-radio.opml" "player-fm-networks-minnesota-public-radio.opml"
MirrorOPML "https://player.fm/networks/mix-1051.opml" "player-fm-networks-mix-1051.opml"
MirrorOPML "https://player.fm/networks/mix-941.opml" "player-fm-networks-mix-941.opml"
MirrorOPML "https://player.fm/networks/mix-945.opml" "player-fm-networks-mix-945.opml"
MirrorOPML "https://player.fm/networks/motley-fool.opml" "player-fm-networks-motley-fool.opml"
MirrorOPML "https://player.fm/networks/music-networks.opml" "player-fm-networks-music-networks.opml"
MirrorOPML "https://player.fm/networks/nbc-news.opml" "player-fm-networks-nbc-news.opml"
MirrorOPML "https://player.fm/networks/nerdist-industries.opml" "player-fm-networks-nerdist-industries.opml"
MirrorOPML "https://player.fm/networks/networks-by-country.opml" "player-fm-networks-networks-by-country.opml"
MirrorOPML "https://player.fm/networks/networks-by-topic.opml" "player-fm-networks-networks-by-topic.opml"
MirrorOPML "https://player.fm/networks/new-books.opml" "player-fm-networks-new-books.opml"
MirrorOPML "https://player.fm/networks/new-zealand-podcast-networks.opml" "player-fm-networks-new-zealand-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/news-networks.opml" "player-fm-networks-news-networks.opml"
MirrorOPML "https://player.fm/networks/newsradio-1020-kdka.opml" "player-fm-networks-newsradio-1020-kdka.opml"
MirrorOPML "https://player.fm/networks/newsradio-1080-krld.opml" "player-fm-networks-newsradio-1080-krld.opml"
MirrorOPML "https://player.fm/networks/nhk-world.opml" "player-fm-networks-nhk-world.opml"
MirrorOPML "https://player.fm/networks/north-american-soccer-network.opml" "player-fm-networks-north-american-soccer-network.opml"
MirrorOPML "https://player.fm/networks/npr.opml" "player-fm-networks-npr.opml"
MirrorOPML "https://player.fm/networks/oam-audio.opml" "player-fm-networks-oam-audio.opml"
MirrorOPML "https://player.fm/networks/open-eyes-network.opml" "player-fm-networks-open-eyes-network.opml"
MirrorOPML "https://player.fm/networks/oracle.opml" "player-fm-networks-oracle.opml"
MirrorOPML "https://player.fm/networks/otago-access-radio.opml" "player-fm-networks-otago-access-radio.opml"
MirrorOPML "https://player.fm/networks/panoply.opml" "player-fm-networks-panoply.opml"
MirrorOPML "https://player.fm/networks/pendant-productions.opml" "player-fm-networks-pendant-productions.opml"
MirrorOPML "https://player.fm/networks/pixelcorps.opml" "player-fm-networks-pixelcorps.opml"
MirrorOPML "https://player.fm/networks/place2be-nation.opml" "player-fm-networks-place2be-nation.opml"
MirrorOPML "https://player.fm/networks/playit.opml" "player-fm-networks-playit.opml"
MirrorOPML "https://player.fm/networks/podcast-networks.opml" "player-fm-networks-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/podnutz.opml" "player-fm-networks-podnutz.opml"
MirrorOPML "https://player.fm/networks/popcorn-talk.opml" "player-fm-networks-popcorn-talk.opml"
MirrorOPML "https://player.fm/networks/premier-christian-radio.opml" "player-fm-networks-premier-christian-radio.opml"
MirrorOPML "https://player.fm/networks/pro-wrestling-report.opml" "player-fm-networks-pro-wrestling-report.opml"
MirrorOPML "https://player.fm/networks/progressive-radio-network.opml" "player-fm-networks-progressive-radio-network.opml"
MirrorOPML "https://player.fm/networks/quick-and-dirty-tips.opml" "player-fm-networks-quick-and-dirty-tips.opml"
MirrorOPML "https://player.fm/networks/rabble-podcast-network.opml" "player-fm-networks-rabble-podcast-network.opml"
MirrorOPML "https://player.fm/networks/radio-adelaide.opml" "player-fm-networks-radio-adelaide.opml"
MirrorOPML "https://player.fm/networks/radio-misfits.opml" "player-fm-networks-radio-misfits.opml"
MirrorOPML "https://player.fm/networks/radiotopia.opml" "player-fm-networks-radiotopia.opml"
MirrorOPML "https://player.fm/networks/rainmakerfm.opml" "player-fm-networks-rainmakerfm.opml"
MirrorOPML "https://player.fm/networks/randomchatter.opml" "player-fm-networks-randomchatter.opml"
MirrorOPML "https://player.fm/networks/raresonance-media.opml" "player-fm-networks-raresonance-media.opml"
MirrorOPML "https://player.fm/networks/red-guerilla-network.opml" "player-fm-networks-red-guerilla-network.opml"
MirrorOPML "https://player.fm/networks/relay-fm.opml" "player-fm-networks-relay-fm.opml"
MirrorOPML "https://player.fm/networks/relic-radio.opml" "player-fm-networks-relic-radio.opml"
MirrorOPML "https://player.fm/networks/restored-life-now.opml" "player-fm-networks-restored-life-now.opml"
MirrorOPML "https://player.fm/networks/ricochet.opml" "player-fm-networks-ricochet.opml"
MirrorOPML "https://player.fm/networks/riotcast-network.opml" "player-fm-networks-riotcast-network.opml"
MirrorOPML "https://player.fm/networks/rocketjump.opml" "player-fm-networks-rocketjump.opml"
MirrorOPML "https://player.fm/networks/rooster-teeth.opml" "player-fm-networks-rooster-teeth.opml"
MirrorOPML "https://player.fm/networks/rotowire.opml" "player-fm-networks-rotowire.opml"
MirrorOPML "https://player.fm/networks/rt-radio-1.opml" "player-fm-networks-rt-radio-1.opml"
MirrorOPML "https://player.fm/networks/sb-nation.opml" "player-fm-networks-sb-nation.opml"
MirrorOPML "https://player.fm/networks/science-networks.opml" "player-fm-networks-science-networks.opml"
MirrorOPML "https://player.fm/networks/secular-media-group.opml" "player-fm-networks-secular-media-group.opml"
MirrorOPML "https://player.fm/networks/shotglass-digital.opml" "player-fm-networks-shotglass-digital.opml"
MirrorOPML "https://player.fm/networks/sideshow-network.opml" "player-fm-networks-sideshow-network.opml"
MirrorOPML "https://player.fm/networks/simply-syndicated.opml" "player-fm-networks-simply-syndicated.opml"
MirrorOPML "https://player.fm/networks/sistah-speak.opml" "player-fm-networks-sistah-speak.opml"
MirrorOPML "https://player.fm/networks/sixgun-productions.opml" "player-fm-networks-sixgun-productions.opml"
MirrorOPML "https://player.fm/networks/slate-magazine.opml" "player-fm-networks-slate-magazine.opml"
MirrorOPML "https://player.fm/networks/smodcast-network.opml" "player-fm-networks-smodcast-network.opml"
MirrorOPML "https://player.fm/networks/society-networks.opml" "player-fm-networks-society-networks.opml"
MirrorOPML "https://player.fm/networks/southgate-media-group.opml" "player-fm-networks-southgate-media-group.opml"
MirrorOPML "https://player.fm/networks/sports-networks.opml" "player-fm-networks-sports-networks.opml"
MirrorOPML "https://player.fm/networks/sportsradio-610.opml" "player-fm-networks-sportsradio-610.opml"
MirrorOPML "https://player.fm/networks/sportsradio-94wip.opml" "player-fm-networks-sportsradio-94wip.opml"
MirrorOPML "https://player.fm/networks/standup-ny-labs.opml" "player-fm-networks-standup-ny-labs.opml"
MirrorOPML "https://player.fm/networks/star-wars-report.opml" "player-fm-networks-star-wars-report.opml"
MirrorOPML "https://player.fm/networks/storytelling-networks.opml" "player-fm-networks-storytelling-networks.opml"
MirrorOPML "https://player.fm/networks/storywonk.opml" "player-fm-networks-storywonk.opml"
MirrorOPML "https://player.fm/networks/talk-radio-1210-wpht.opml" "player-fm-networks-talk-radio-1210-wpht.opml"
MirrorOPML "https://player.fm/networks/talking-comics.opml" "player-fm-networks-talking-comics.opml"
MirrorOPML "https://player.fm/networks/tech-networks.opml" "player-fm-networks-tech-networks.opml"
MirrorOPML "https://player.fm/networks/the-association-of-music-podcasting.opml" "player-fm-networks-the-association-of-music-podcasting.opml"
MirrorOPML "https://player.fm/networks/the-average-guy.opml" "player-fm-networks-the-average-guy.opml"
MirrorOPML "https://player.fm/networks/the-beast-980.opml" "player-fm-networks-the-beast-980.opml"
MirrorOPML "https://player.fm/networks/the-brewing-network.opml" "player-fm-networks-the-brewing-network.opml"
MirrorOPML "https://player.fm/networks/the-bulls-podcasters.opml" "player-fm-networks-the-bulls-podcasters.opml"
MirrorOPML "https://player.fm/networks/the-dice-tower-network.opml" "player-fm-networks-the-dice-tower-network.opml"
MirrorOPML "https://player.fm/networks/the-geekbox.opml" "player-fm-networks-the-geekbox.opml"
MirrorOPML "https://player.fm/networks/the-incomparable.opml" "player-fm-networks-the-incomparable.opml"
MirrorOPML "https://player.fm/networks/the-naked-scientists.opml" "player-fm-networks-the-naked-scientists.opml"
MirrorOPML "https://player.fm/networks/the-pod-gods.opml" "player-fm-networks-the-pod-gods.opml"
MirrorOPML "https://player.fm/networks/the-royal-half.opml" "player-fm-networks-the-royal-half.opml"
MirrorOPML "https://player.fm/networks/the-sports-stuff.opml" "player-fm-networks-the-sports-stuff.opml"
MirrorOPML "https://player.fm/networks/the-stn.opml" "player-fm-networks-the-stn.opml"
MirrorOPML "https://player.fm/networks/the-wellness-couch.opml" "player-fm-networks-the-wellness-couch.opml"
MirrorOPML "https://player.fm/networks/today-network.opml" "player-fm-networks-today-network.opml"
MirrorOPML "https://player.fm/networks/toginet.opml" "player-fm-networks-toginet.opml"
MirrorOPML "https://player.fm/networks/triple-j.opml" "player-fm-networks-triple-j.opml"
MirrorOPML "https://player.fm/networks/triple-m.opml" "player-fm-networks-triple-m.opml"
MirrorOPML "https://player.fm/networks/twit.opml" "player-fm-networks-twit.opml"
MirrorOPML "https://player.fm/networks/uk-podcast-networks.opml" "player-fm-networks-uk-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/unity-online-radio.opml" "player-fm-networks-unity-online-radio.opml"
MirrorOPML "https://player.fm/networks/us-995.opml" "player-fm-networks-us-995.opml"
MirrorOPML "https://player.fm/networks/us-podcast-networks.opml" "player-fm-networks-us-podcast-networks.opml"
MirrorOPML "https://player.fm/networks/voice-of-america.opml" "player-fm-networks-voice-of-america.opml"
MirrorOPML "https://player.fm/networks/waterlogg-productions.opml" "player-fm-networks-waterlogg-productions.opml"
MirrorOPML "https://player.fm/networks/wbbm-newsradio.opml" "player-fm-networks-wbbm-newsradio.opml"
MirrorOPML "https://player.fm/networks/wbur-fm.opml" "player-fm-networks-wbur-fm.opml"
MirrorOPML "https://player.fm/networks/wbz-newsradio-1030.opml" "player-fm-networks-wbz-newsradio-1030.opml"
MirrorOPML "https://player.fm/networks/wcbs-newsradio-880.opml" "player-fm-networks-wcbs-newsradio-880.opml"
MirrorOPML "https://player.fm/networks/web-talk-radio.opml" "player-fm-networks-web-talk-radio.opml"
MirrorOPML "https://player.fm/networks/wfan.opml" "player-fm-networks-wfan.opml"
MirrorOPML "https://player.fm/networks/wkms.opml" "player-fm-networks-wkms.opml"
MirrorOPML "https://player.fm/networks/wnew-991-fm.opml" "player-fm-networks-wnew-991-fm.opml"
MirrorOPML "https://player.fm/networks/wnyc.opml" "player-fm-networks-wnyc.opml"
MirrorOPML "https://player.fm/networks/wolfpop.opml" "player-fm-networks-wolfpop.opml"
MirrorOPML "https://player.fm/networks/wpgc-955.opml" "player-fm-networks-wpgc-955.opml"
MirrorOPML "https://player.fm/networks/wwj-newsradio-950.opml" "player-fm-networks-wwj-newsradio-950.opml"
MirrorOPML "https://player.fm/networks/y98.opml" "player-fm-networks-y98.opml"
MirrorOPML "https://player.fm/networks/z-1077-fm.opml" "player-fm-networks-z-1077-fm.opml"
MirrorOPML "https://player.fm/networks/zoomer-radio.opml" "player-fm-networks-zoomer-radio.opml"

